# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/devcontainers/go:1.20

RUN apt-get update && apt-get upgrade

# WORKDIR /root/

# go install golang.org/dl/go$(cat .go-version)@latest && \
# go$(cat .go-version) download
# export GOROOT=$(go1.18 env GOROOT)
# export PATH=${GOROOT}/bin;${PATH}

# Install:
# go
# dlv
# gomodifytags
# goplay
# gopls
# gotests
# impl
# mage
# staticcheck